### PR TITLE
Edit byline

### PR DESCRIPTION
**Pull request by chrisalcantara**
Hello!

Thanks for this great plugin. 

I didn't like title case for the names -- hard to see in some cases -- and changed each to uppercase, per NYT styles. I also added "By" before each name.

### CODE REVIEW

**Comment by johnhawkinson** [comment]
There's some irony here. The RSS feed uses BLOCK UPPERCASE and Dan's code goes to some special effort to attempt to return it to Title Case. So with your patch, the byline starts in uppercase, gets converted to lowercase with selective title-casing, and then forced back to uppercase.

While we're here, my user script to do this that predates Dan's extension (cf. https://gist.github.com/johnhawkinson/7400d0f19158b1bbcc2b5319bbc8d451) uses this (ugly) function to fix up case:

```js
  // This is much better, but is harder to read. Given these specials:
  //       <dc:creator>DONALD G. McNEIL Jr.</dc:creator>
  //       <dc:creator>ISABELLA KWAI and CHARLOTTE GRAHAM-McLAY</dc:creator>
  // Algorithm: Go char by char; if previous char is uppercase,
  // then lowercase the current, otherwise as-is. First character is always
  // as-is.
  function NYTtitleCase(s) {
    var n, i, o, olower;
    n = s.charAt(0);
    for (i=1; i<s.length; i++) {
  		o = s.charAt(i-1);
      olower = o.toLowerCase();
      if (o !== olower) {
        n = n + s.charAt(i).toLowerCase();
      } else {
        n = n + s.charAt(i);
      }
    }
    return n;
  }
```

Dan might want to adopt it, or something similar.

I don't use Dan's extension, but I prefer to see title case here, although I realize it makes the homepage look different from the section fronts (among other things).

**Comment by chrisalcantara** [comment]
Thanks, @johnhawkinson. You're correct. The code is redundant. I prefer the uppercase (Dan should have the final say) and will update my code.

**Comment by dstillman** [comment]
Thanks to you both. Yeah, I opted against the block caps, even though they're on the section pages.  Personally I find them anachronistic, they're not used on the article pages, and in general I just tried to match what's already in use on the homepage for opinion bylines and photo credits, which is serif and title case. I left off the "By" for the same reason, and because showing it 50 times seemed redundant, though that one's debatable.

Re: the title case function, I didn't notice any names in the feeds that actually used lowercase letters for "Mc" or similar. @johnhawkinson, have you seen that in the wild? If so, I can certainly account for it.

**Comment by johnhawkinson** [comment]
>  @johnhawkinson, have you seen that in the wild? If so, I can certainly account for it.

Yes. The two examples in the comment above the function (DONALD G. McNEIL Jr., CHARLOTTE GRAHAM-McLAY) were real examples (back on the day I wrote that code...Aug. 24). It appears there aren't any on the homepage right now, though:

```
pb3:tmp jhawk$ curl -s  https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml | sed -n -e 's/ and//' -e 's/dc:creator//gp' | grep '[a-z]'
pb3:tmp jhawk$ 
```
But you can still find CG-M in the Americas and World feeds (e.g. https://www.nytimes.com/services/xml/rss/nyt/Americas.xml):

```xml
    <item>
      <title>Maori Language, Once Shunned, Is Having a Renaissance in New Zealand</title>
      <link>https://www.nytimes.com/2018/09/16/world/asia/new-zealand-maori-language.html?partner=rss&amp;emc=rss</link>
      <guid isPermaLink="true">https://www.nytimes.com/2018/09/16/world/asia/new-zealand-maori-language.html</guid>
      <atom:link rel="standout" href="https://www.nytimes.com/2018/09/16/world/asia/new-zealand-maori-language.html?partner=rss&amp;emc=rss"/>
      <media:content url="https://static01.nyt.com/images/2018/09/17/world/00nz-maori-1/00nz-maori-1-moth.jpg" medium="image" height="151" width="151"/>
      <media:description>Residents of Merivale Retirement Village practicing Maori with their activities coordinator, Tim Belcher, in Christchurch, New Zealand, last month.</media:description>
      <media:credit>Birgit Krippner for The New York Times</media:credit>
      <description>Indigenous people are increasingly embracing their language while New Zealanders of European descent are looking to Maori language and culture to help make sense of their own identity.</description>
      <dc:creator>CHARLOTTE GRAHAM-McLAY</dc:creator>
      <pubDate>Sun, 16 Sep 2018 19:00:04 GMT</pubDate>
      <category domain="http://www.nytimes.com/namespaces/keywords/des">Maoris</category>
      <category domain="http://www.nytimes.com/namespaces/keywords/des">Language and Languages</category>
      <category domain="http://www.nytimes.com/namespaces/keywords/nyt_geo">New Zealand</category>
      <category domain="http://www.nytimes.com/namespaces/keywords/des">Politics and Government</category>
    </item>
```

Across all of these, DGM is the most prolific:

```
pb3:nyt jhawk$ cat *.xml  | sed -n -e 's/ and//' -e 's/dc:creator//gp' | grep '[a-z]' | sort | uniq -c | sort -nr | head
   6       <>DONALD G. McNEIL Jr.</>
   4       <>MICHAEL J. de la MERCED</>
   4       <>Compiled by PETER LIBBEY</>
   3       <>TIM McKEOUGH</>
   3       <>JER&#xC9; LONGMAN</>
   2       <>ROBERT D. McFADDEN</>
   2       <>MICHAEL O&#x2019;DONNELL</>
   2       <>LISA McGIRR</>
   2       <>JOSE SOL&#xCD;S</>
   2       <>ELISABETTA POVOLEDO RICHARD P&#xC9;REZ-PE&#xD1;A</>
```

**Comment by chrisalcantara** [comment]
The "By" and uppercase names seem to be more aesthetic choices than improvements to the script. I like the uppercase and "by," so I'll probably keep using my fork of this script. I can close this PR if you want, @dstillman.

**Comment by dstillman** [comment]
OK, I've added John's title-casing function. I'm going to leave the styling of the bylines as is for now.

Thanks again to both of you!

**Pull request closed without merging**
